name: Pull Component Documentation

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'  # Runs every Sunday at midnight UTC

permissions:
  contents: write

jobs:
  update-template:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}

      - name: Clone BookShop Starter
        run: git clone --depth 1 https://github.com/Virtuouz/BookShopStarter.git

      - name: Copy Component Library
        run: |
          mkdir -p src/docs/Components
          
          # Find all markdown files and copy them based on tags
          find BookShopStarter/_component-library -type f -name "*.md" | while read -r file; do
            # Extract the tag without the "tags: " prefix
            tag=$(grep -E '^tags: ' "$file" | sed -E 's/tags:\s*\[?"?([^",\]]+).*/\1/' | tr -d '"')
            
            # Only proceed if a tag was found
            if [[ -n "$tag" ]]; then
              # Create the directory based on the first tag and copy the file
              mkdir -p "src/docs/Components/$tag"
              cp "$file" "src/docs/Components/$tag/$(basename "$file")"
            else
              echo "No tag found in $file"
            fi
          done

      - name: Commit and push changes
        run: |
          git config --global user.email "github-actions-bot@users.noreply.github.com"
          git config --global user.name "GitHub Actions Bot"
          git checkout -b autoDocs || git checkout autoDocs
          git pull origin autoDocs --rebase  # Pull the latest changes before pushing
          git add src/docs/Components
          git commit -m "Update component library from BookShop Starter" || echo "No changes to commit"
          git push origin autoDocs

      - name: Create Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_DATA=$(jq -n --arg title "Update component library from BookShop Starter" \
                           --arg body "This PR updates the component library from BookShop Starter." \
                           --arg head "autoDocs" \
                           --arg base "main" \
                           '{title: $title, body: $body, head: $head, base: $base}')
          curl -s -X POST -H "Authorization: token $GITHUB_TOKEN" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/repos/${{ github.repository }}/pulls \
               -d "$PR_DATA"
