name: Pull Component Documentation

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'  # Runs every Sunday at midnight UTC

permissions:
  contents: write
  pull-requests: write

jobs:
  update-template:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}

      - name: Clone BookShop Starter
        run: git clone --depth 1 https://github.com/Virtuouz/BookShopStarter.git

      - name: Copy Component Library
        run: |
          mkdir -p src/docs/Components
          echo "Starting to copy component library..."
          # Find all markdown files and copy them based on tags
          find BookShopStarter/_component-library -type f -name "*.md" | while read -r file; do
            echo "Processing file: $file"
            tag=$(grep -E '^tags:\s*(.+)$' "$file" | sed -E 's/^tags:\s*\[?"?([^",\]]+).*/\1/' | tr -d '"')
            # Remove any leading or trailing whitespace from the extracted tag
            tag=$(echo "$tag" | xargs)
            if [[ -n "$tag" ]]; then
              echo "Found tag: $tag"
              mkdir -p "src/docs/Components/$tag"
              cp -f "$file" "src/docs/Components/$tag/$(basename "$file")"
              echo "Copied $file to src/docs/Components/$tag (overwritten if existed)"
            else
              echo "No tag found in $file"
            fi
          done
          echo "Completed copying component library."



      - name: Commit and push changes
        run: |
          git config --global user.email "github-actions-bot@users.noreply.github.com"
          git config --global user.name "GitHub Actions Bot"
          git checkout -b autoDocs || git checkout autoDocs
          git add src/docs/Components
          git commit -m "Update component library from BookShop Starter" || echo "No changes to commit"
          git push -f origin autoDocs  # Force push to overwrite remote

      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_EXISTS=$(gh pr list --state=open --head autoDocs | wc -l)
          if [[ "$PR_EXISTS" == "0" ]]; then
            gh pr create --title "Update component library from BookShop Starter" --body "This PR updates the component library from BookShop Starter." --base main --head autoDocs
          else
            echo "PR already exists for autoDocs branch"
          fi
