name: Pull Component Documentation

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'  # Runs every Sunday at midnight UTC

permissions:
  contents: write

jobs:
  update-template:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}

      - name: Clone BookShop Starter
        run: git clone --depth 1 https://github.com/Virtuouz/BookShopStarter.git

      - name: Copy Component Library
        run: |
          mkdir -p src/docs/Components
          # Find all markdown files and copy them based on tags
          find BookShopStarter/_component-library -type f -name "*.md" | while read -r file; do
            tag=$(grep -E '^tags: (.+)$' "$file" | sed -E 's/tags: \[?"?([^",\]]+).*/\1/' | tr -d '"')
            if [[ -n "$tag" ]]; then
              mkdir -p "src/docs/Components/$tag"
              cp "$file" "src/docs/Components/$tag/$(basename "$file")"
            else
              echo "No tag found in $file"
            fi
          done

      - name: Stage and Commit Changes
        run: |
          git config --global user.email "github-actions-bot@users.noreply.github.com"
          git config --global user.name "GitHub Actions Bot"
          git add src/docs/Components
          git commit -m "Temporary commit for untracked files"

      - name: Switch to autoDocs Branch
        run: |
          git fetch origin autoDocs:autoDocs || echo "autoDocs branch does not exist"
          git rebase autoDocs  # Use rebase to avoid checkout conflicts
          git add src/docs/Components
          git commit -m "Update component library from BookShop Starter" --allow-empty
          git push origin autoDocs --force  # Force push if necessary

      - name: Create Pull Request
        run: |
          PR_EXISTS=$(gh pr list --state=open --head autoDocs | wc -l)
          if [[ "$PR_EXISTS" == "0" ]]; then
            gh pr create --title "Update component library from BookShop Starter" --body "This PR updates the component library from BookShop Starter." --base main --head autoDocs
          else
            echo "PR already exists for autoDocs branch"
          fi
